C = gcc
CXX = g++

# SOURCE_C = 
# OBJECTS_C = 
SOURCE_CXX = demo1.cpp

TARGET = 1.1
LDFLAGS_COMMON = -std=c++2a

all:
	# $(C) -c $(SOURCE_C)
	$(CXX) $(SOURCE_CXX) $(LDFLAGS_COMMON) -o $(TARGET)

clean:
	rm -rf *.o $(TARGET)



